services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: hono-app:latest
    container_name: hono-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bun", "fetch", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    # Uncomment to add volume for logs
    # volumes:
    #   - ./logs:/app/logs

  # Example: Add PostgreSQL database
  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # Example: Add Redis cache
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis-cache
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   postgres-data:
